### ISSUE TITLE
VPS' that send the root password per email

### ISSUE THREAD

**Issue by Bloodyfool** [Tribler/cloudomate#66]
While implementing LibertyVPS i found that they send the root password per email. Luckily this email can be viewed from the client area as well. The password can be automatically acquired when the server has been set up, but cloudomate lacks a mechanism to do so. What would be a good way of dealing with this?

I have the following ideas:
 - On purchase, leave the password empty in the config and automatically update the password the first time the "status" command returns Online = True.
 - Add a command to "getPasswordFromEmail"
 - Add a fallback in the "ssh" and/or "setrootpw" commands to a password from the email

**Comment by synctext** [comment]
Did you find email handling code in original cloudomate?
https://github.com/Tribler/cloudomate/blob/develop/cloudomate/test/resources/crowncloud_email.html

**Comment by MattSkala** [comment]
@Bloodyfool E-mail parsing is already implemented for some providers as part of the `info` command. The downside of this solution is that we have to login to the client area and parse the e-mail on every call of this command, but I think it's good enough for our use case. Take a look at the `get_configuration` method of BlueAngelHost for example.
